### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by CCC-9527** [Thomilist/show-durability#3]
![2023-04-05_13 13 57](https://user-images.githubusercontent.com/129697452/229987731-8c7e9e90-5fd2-416e-a5f2-2a553647a5a4.png)

**Comment by Thomilist** [comment]
Hello

Is this related to issue #2? If not, please explain the problem in greater detail. I'm not able to understand the problem from the picture alone.

Also, if the resource pack is relevant, please provide a link to that as well.

Thank you

**Comment by alexweber** [comment]
@Thomilist I think he's trying to say that the durability is displaying on all items, always.  The screenshot is from creative mode, I can verify it happens.

**Comment by Thomilist** [comment]
@alexweber Hmm, you're probably right. Thank you.

It does indeed show up in creative mode, but that is intentional (and a bit less significant now that there's a toggle hotkey). However, the durability numbers showing up on the tools on the tabs in the creative menu (the diamond pickaxe and sword on the bottom left in the picture) is not intentional. It's been that way from the start, but if I find a way to prevent it, I definitely will.

**Comment by alexweber** [comment]
@Thomilist Confirm that the workaround above resolves the issue... it also changes the behavior somewhat by only dispalying the durability once the item is damaged so your call as to whether to include it or not.  I like it to be honest! :)

**Comment by alexweber** [comment]
In fact, you don't even need to check for `isDamageable()` anymore with `isDamaged()`

**Comment by Thomilist** [comment]
@alexweber Oh thank you, that's pretty neat. I like the simplicity of that solution, but unfortunately(?) I also like seeing durability numbers on undamaged items, so I don't think I will take it. But still, thank you for trying around a bit :)
